#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
python neural_style_transfer_app_panel.py "$@"

# python neural_style_transfer.py --content_img_name "lion.jpg" --style_img_name "mosaic.jpg" --saving_freq 1
